### ISSUE TITLE
[Missing Driver]: falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.ko

### ISSUE THREAD

**Issue by tigardis** [falcosecurity/test-infra#1093]
**Describe the bug**

> falco-driver-loader * Looking for a falco module locally (kernel 5.4.238-148.346.amzn2.x86_64)
> falco-driver-loader * Filename 'falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.ko' is composed of:
> falco-driver-loader  - driver name: falco
> falco-driver-loader  - target identifier: amazonlinux2
> falco-driver-loader  - kernel release: 5.4.238-148.346.amzn2.x86_64
> falco-driver-loader  - kernel version: 1
> falco-driver-loader * Trying to download a prebuilt falco module from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.ko
> falco-driver-loader curl: (22) The requested URL returned error: 404

**How to reproduce it**

1. Start/install Falco on Amazon Linux2 5.4.238-148.346

**Expected behaviour**

Startup succeeds after locating driver

**Screenshots**

**Environment**

- Falco version:

Below is from our Prod cluster - Falco doesn't start in our test cluster. I have tried deploying falco v3.1.3 but it does not solve the problem.

> Tue Apr 11 20:33:07 2023: Falco version: 0.34.0 (x86_64)
> Tue Apr 11 20:33:07 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
> Falco version: 0.34.0
> Libs version:  0.10.3
> Plugin API:    2.0.0
> Engine:        15
> Driver:
>   API version:    3.0.0
>   Schema version: 2.0.0
>   Default driver: 4.0.0+driver

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:
AWS EKS - Kubernetes v1.23.17 (Helm chart 3.0.0 or 3.1.3)

**Additional context**

**Comment by FedeDP** [comment]
Hi! 
We have `5.4.238-148.347`: https://download.falco.org/driver/site/index.html?lib=4.0.0%2Bdriver&target=amazonlinux2&arch=x86_64&kind=kmod
I think you need to upgrade your kernel to latest version! We did never build `5.4.238-148.346` unfortunately; most probably it was immediately patched to `.347` and since our pipeline runs weekly, we only discovered and built the latter.

**Comment by renilthomas** [comment]
The EKS latest AMI [release](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230406) has pinned `5.4.238-148.346.amzn2` for k8s v1.23 or below. Can the kernel crawler build based on a  specific version?
At this stage, there are some critical vulnerabilities that is addressed in this new AMI but we have only two options:
1. Disable falco and upgrade AMI
2. Upgrade k8s - which obviously requires scheduling a maintenance and planning towards it.

**Comment by FedeDP** [comment]
Hi! It seems like we fail to crawl the kernel; i will look into this asap :)

**Comment by renilthomas** [comment]
Thank you @FedeDP 🙇

**Comment by FedeDP** [comment]
Mmh my guess is that the `5.4.238-148.346.amzn2` kernel is not present in any mirror anymore; as i said previously, we can only scrape `5.4.238-148.347.amzn2`.
Are you able to share the url for the `5.4.238-148.346.amzn2` package?

**Comment by renilthomas** [comment]
I got this URL from the instance with the specific kernel version

https://amazonlinux-2-repos-us-west-2.s3.dualstack.us-west-2.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/2d43c5da4c1aee506efc1db66eca9864d37d1f92076bd0eb8b357c32189079bf/../../../../../../blobstore/6e296e6f7ea2f7f03d201ac21967f5c61bdb7904485492cc822b34d6892af4c8/kernel-5.4.238-148.346.amzn2.x86_64.rpm?instance_id=i-06180ff90d192c97f&region=us-west-2

**Comment by FedeDP** [comment]
For reference, this is what the crawler finds instead:
http://amazonlinux.us-west-2.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61/../../../../../../blobstore/fa5caa71652bca6f4a8aeff9356d18bd1785d8620080398768acbb53a7fb5756/kernel-devel-5.4.238-148.347.amzn2.x86_64.rpm

**Comment by renilthomas** [comment]
Yes i have seen that running kernel-crawler myself. Is it possible to build with that URL I shared? Thank you in advance!

**Comment by FedeDP** [comment]
The quickest fix, since you have the full URL, is to add a new config on test-infra for it by eg: copy/paste the `347` one: https://github.com/falcosecurity/test-infra/blob/master/driverkit/config/4.0.0%2Bdriver/x86_64/amazonlinux2_5.4.238-148.347.amzn2.x86_64_1.yaml

If you open a PR (please add it for all 3 supported driver versions!) i will be happy to accept it :)

**Comment by renilthomas** [comment]
Brilliant, on it.. Thanks @FedeDP

**Comment by FedeDP** [comment]
In the meantime, i am trying to figure out what are we missing :)
Also, @EXONER4TED (gentle tag ahah) is the :crown: when finding weird kernel-crawler issues :D

**Comment by FedeDP** [comment]
Wait! i just notice: you are sharing the kernel URL, not the `kernel-devel` one.
Perhaps there is no kernel-devel package for it?

**Comment by renilthomas** [comment]
oh right, checking

**Comment by renilthomas** [comment]
You are right, there seems to be none for 346 😞

**Comment by FedeDP** [comment]
So, did they push an updated kernel without pushing updated headers? That would be really weird...

**Comment by renilthomas** [comment]
I am checking with AWS directly, yes if that is the case it is truly absurd.

**Comment by FedeDP** [comment]
I still don't get where does this kernel version come from; doing a 
```
wget amazonlinux.us-west-2.amazonaws.com/2/extras/kernel-5.4/latest/x86_64/mirror.list
```
yelds a mirror.list file with 
```
http://amazonlinux.us-east-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61
```
as a content. That is what kernel-crawler is discovering too.
There should not be any other mirror, as far as i could find, for kernel-5.4.

**Comment by eelkoniovb** [comment]
We also suffer from this problem. It's happened before, about two years ago I think.

I've already asked AWS Support to fix this. Indeed, there are no entries for the newest AMI in their package list. We build the falco module via the driverkit, but it fails as there are no package entries for this new AMI kernel version:

Step by step; when you retrieve this:

[http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/latest/x86_64/mirror.list ](http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/latest/x86_64/mirror.list) 

..it returns this URL: [http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61 ](http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61) 

When retrieving this as an sqlite database:
[http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61/repodata/primary.sqlite.gz ](http://amazonlinux.eu-central-1.amazonaws.com/2/extras/kernel-5.4/stable/x86_64/437c15a145ce03d3a48b7fd7559df3851f3b58fd9d7a78960f44d029f145bd61/repodata/primary.sqlite.gz) 


...we get a database that holds no info for the latest AMI version, but several entries for the ones before:

% gunzip primary.sqlite.gz ; sqlite3 primary.sqlite
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> select rpm_sourcerpm from packages where rpm_sourcerpm like "%5.4.235-144.344%";
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
kernel-5.4.235-144.344.amzn2.src.rpm
sqlite> select rpm_sourcerpm from packages where rpm_sourcerpm like "%5.4.238-148.346.amzn2.x86_64%";
sqlite> 

My AWS support person has not yet understood this is the problem, or cannot find the people involved for this sqlite database. My guess is not the latter, unfortunately.

Cheers,
   Eelko

**Comment by FedeDP** [comment]
Yep, our [kernel-crawler](https://github.com/falcosecurity/kernel-crawler) does exactly the same thing; and indeed it cannot find this specific kernel.
To me, this seems like an aws internal issue; let's see.

**Comment by tigardis** [comment]
Sure thing.
@FedeDP we are using the latest available AWS verified AMI for 1.23
(ami-0559f43d314aa2e7e), and as others have mentioned upgrading K8s to 1.24
will require more planning. At this point I am most likely going to try
downgrading to an earlier AMI since this version was missed due to pipeline
configuration.

**Comment by mpurusottamc** [comment]
We are also facing similar issue with latest AWS EKS AMI for 1.23. We have tried to downgrade the ami and it seems to be working.

@renilthomas Thanks for working with the ec2 team. Please share if you hear any updates.

**Comment by mpurusottamc** [comment]
@renilthomas AWS has updated the AMIs and the updated AMI uses kernel version `5.4.238-148.347.amzn2.x86_64`. We did an initial testing and falco probe is getting downloaded properly and is working properly now.
cc: @FedeDP

**Comment by mpurusottamc** [comment]
Release details are here: https://github.com/awslabs/amazon-eks-ami/releases

**Comment by renilthomas** [comment]
That is correct, they responded to my issue https://github.com/awslabs/amazon-eks-ami/issues/1266#issuecomment-1515110366
And I had also escalated it within AWS and last I heard earlier was they were working on the fix.

**Comment by FedeDP** [comment]
So, this was an issue on the AWS side right?
Great to hear it's getting fixed!:)

**Comment by FedeDP** [comment]
I am going to pin this issue since it caused multiple headaches :D
