### ISSUE TITLE
Enable prow for contrib repo

### ISSUE THREAD

**Issue by leodido** [falcosecurity/test-infra#111]
**Motivation**

All the repos must follow the contributing guidelines and having the tooling enforcing them

**Feature**

Enable @poiana on https://github.com/falcosecurity/contrib

**Additional context**

The https://github.com/falcosecurity/contrib repository will contain all the integrations of Falco in other environments provided by the community.

**Comment by leogr** [comment]
It seems to me this was already fixed by https://github.com/falcosecurity/test-infra/pull/113

@leodido 
Is there something missing? If it isn't, we can close this
