### ISSUE TITLE
[Missing driver] latest ubuntu-aws_5.19.0 driver

### ISSUE THREAD

**Issue by mathiasboostai** [falcosecurity/test-infra#1114]
**Describe the bug**

The newest ubuntu-aws driver is not built yet, 9 days since the new kernel release was published.
From the logs of the failed falco startup:
```
* Looking for a falco module locally (kernel 5.19.0-1024-aws)
* Filename 'falco_ubuntu-aws_5.19.0-1024-aws_25.ko' is composed of:
 - driver name: falco
 - target identifier: ubuntu-aws
 - kernel release: 5.19.0-1024-aws
 - kernel version: 25
* Trying to download a prebuilt falco module from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_ubuntu-aws_5.19.0-1024-aws_25.ko
curl: (22) The requested URL returned error: 404 
```
I see the last driver of that type was published 6 days after kernel release publish, so i was wondering if there is some sort of schedule for this type of jobs or if the time between kernel release and falco driver is just random? 

**How to reproduce it**

Start falco on server using kernel release: 5.19.0-1024-aws

**Expected behaviour**

Startup downloading driver and succeed

**Screenshots**

**Environment**

- Falco version: 0.34.1

- System info:

- Cloud provider or hardware configuration: AWS
- OS: ubuntu 22.04

- Kernel: 

- Installation method: docker-compose 

**Additional context**

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue! 
I am trying to fix up our kernel-crawler CI right now; after that, it should be able to correctly find the new driver :crossed_fingers: 

I made a local run of the crawler and it did find the kernel:
```
{
      "kernelversion": "25",
      "kernelrelease": "5.19.0-1024-aws",
      "target": "ubuntu-aws",
      "headers": [
        "http://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws/linux-aws-headers-5.19.0-1024_5.19.0-1024.25_all.deb",
        "http://security.ubuntu.com/ubuntu/pool/main/l/linux-aws/linux-headers-5.19.0-1024-aws_5.19.0-1024.25_amd64.deb",
        "http://security.ubuntu.com/ubuntu/pool/main/l/linux-aws/linux-aws-headers-5.19.0-1024_5.19.0-1024.25_all.deb",
        "http://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-aws/linux-headers-5.19.0-1024-aws_5.19.0-1024.25_amd64.deb"
      ]
    },
```

Let's wait on the CI :)

**Comment by FedeDP** [comment]
Update: the CI is now building drivers: https://prow.falco.org/view/s3/falco-prow-logs/logs/build-new-drivers-ubuntu-aws-5-postsubmit/1653369262653313024

**Comment by FedeDP** [comment]
Prebuilt driver is now built: https://prow.falco.org/view/s3/falco-prow-logs/logs/build-new-drivers-ubuntu-aws-5-postsubmit/1653369262653313024
The issue should be fixed!

**Comment by mathiasboostai** [comment]
Great! Thanks for quick response :)
