### ISSUE TITLE
Check owners are already part of the GitHub organization

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#1126]
**Motivation**

When an open PR introduces a change on an [OWNERS](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#overview) file introducing a user which is not already part of the organization, the user should be part of the organization before the change on the file.

Otherwise, it would be possible to merge the PR if the new user still needs to join the org.

**Feature**

Develop a plugin that provides a CI pre-check to check that the required member is part of the organization - by checking the Peribolos [organization config](https://docs.prow.k8s.io/docs/components/cli-tools/peribolos/#org-configuration).

The check should be required and should fail when the user is not present in the [`organization.members`](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml#L21).

**Alternatives**

Automate in some way the Peribolos configuration update, after the PR which introduces a new owner is merged.

**Additional context**

- Falcosecurity GitHub configuration is managed with [Peribolos](https://docs.prow.k8s.io/docs/components/cli-tools/peribolos) that supports declarative configuration.
- There is an [automation](https://github.com/falcosecurity/test-infra/blob/master/config/jobs/update-github-teams/peribolos-syncer.yaml) in place (now in a rollout phase - supported as of now only by the evolution repository as a preview) that updates maintainers' GitHub teams with approvers in the [OWNERS](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#overview).

**Comment by maxgio92** [comment]
Actually, this should be the responsibility of the [verify-owners](https://github.com/kubernetes/test-infra/blob/7b55e5587d66478ac85ce8e328d3d9c75af5cd7a/prow/plugins/verify-owners/verify-owners.go#L267) Prow plugin.
To be verified.

**Comment by leogr** [comment]
The verify-owner plugin already does that. The only difference is that it's not a GitHub check. However, it already works fine with the prow workflow. Likely we don't need any improvement.

**Comment by maxgio92** [comment]
What do you mean by GitHub check? I think it actually checks at runtime that the user is part of the organization, directly from github API.

**Comment by leogr** [comment]
I meant:

The `verify-owner` plugin already does the same thing by using prow and it uses labels to block the PR from being merged, not [GitHub status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks). 

Here's an example of `verify-owner` in action: https://github.com/falcosecurity/driverkit/pull/259#issuecomment-1484838796
It shows that it's not possible to merge the PR before the member joins the org.

Thus, since `verify-owner` does the job yet, this :point_down: is likely unnecessary

> Develop a plugin that provides a CI pre-check to check that the required member is part of the organization - by checking the Peribolos [organization config](https://docs.prow.k8s.io/docs/components/cli-tools/peribolos/#org-configuration).

Am I missing anything? :thinking:

**Comment by leogr** [comment]
Btw, this :point_down: is already not possible
> Otherwise, it would be possible to merge the PR if the new user still needs to join the org.

**Comment by maxgio92** [comment]
I think you're right. I think I misunderstood your comment [here](https://github.com/falcosecurity/test-infra/issues/777#issuecomment-1481181497)
