### ISSUE TITLE
Failed to download prebuilt module falco_amazonlinux2_5.10.186-179.751.amzn2.x86_64_1.ko on EKS AMI AMI Release v20230816

### ISSUE THREAD

**Issue by ian659** [falcosecurity/test-infra#1220]
**Describe the bug**

```
2023-08-22T15:20:12.642645872Z * Looking for a falco module locally (kernel 5.10.186-179.751.amzn2.x86_64)
2023-08-22T15:20:12.642658291Z * Filename 'falco_amazonlinux2_5.10.186-179.751.amzn2.x86_64_1.ko' is composed of:
 - driver name: falco
2023-08-22T15:20:12.642663903Z  - target identifier: amazonlinux2
 - kernel release: 5.10.186-179.751.amzn2.x86_64
 - kernel version: 1
* Trying to download a prebuilt falco module from https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_amazonlinux2_5.10.186-179.751.amzn2.x86_64_1.ko
2023-08-22T15:20:12.673271643Z curl: (22) The requested URL returned error: 404 
2023-08-22T15:20:12.674894918Z Unable to find a prebuilt falco module
```

**How to reproduce it**

Attempt to run on [latest EKS AMI](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230816).

**Expected behaviour**

Should successfully startup

**Screenshots**

**Environment**

- Falco version: docker.io/falcosecurity/falco-driver-loader:0.35.1

- System info:

- Cloud provider or hardware configuration: Amazon EKS v1.26.7 -2d98532
- OS: Amazon Linux 2

- Kernel: 5.10.186-179.751.amzn2.x86_64

- Installation method: Kubernetes Helm

**Additional context**

**Comment by s7an-it** [comment]
* Setting up /usr/src links from host
18
* Running falco-driver-loader for: falco version=0.35.1, driver version=5.0.1+driver, arch=x86_64, kernel release=5.10.186-179.751.amzn2.x86_64, kernel version=1
17
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
16
* Mounting debugfs
15
mount: /sys/kernel/debug: permission denied.
14
* Filename 'falco_amazonlinux2_5.10.186-179.751.amzn2.x86_64_1.o' is composed of:
13
 - driver name: falco
12
 - target identifier: amazonlinux2
11
 - kernel release: 5.10.186-179.751.amzn2.x86_64
10
 - kernel version: 1
9
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_amazonlinux2_5.10.186-179.751.amzn2.x86_64_1.o
8
curl: (22) The requested URL returned error: 404
7
Unable to find a prebuilt falco eBPF probe
6
* Trying to compile the eBPF probe (falco_amazonlinux2_5.10.186-179.751.amzn2.x86_64_1.o)
5
expr: syntax error: unexpected argument '1'
4
make[1]: *** /lib/modules/5.10.186-179.751.amzn2.x86_64/build: No such file or directory.  Stop.
3
make: *** [Makefile:38: all] Error 2
2
mv: cannot stat '/usr/src/falco-5.0.1+driver/bpf/probe.o': No such file or directory
1
Unable to load the falco eBPF probe

**Comment by ian659** [comment]
@maxgio92 This resolved in my clusters at approximately 7am EDT today. Closing since this seems to be resolved, thank you.
