### ISSUE TITLE
Port driverkit build grid away from makefile and bash scripts

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/test-infra#1221]
**Motivation**

Current Makefile and bash scripts are convoluted, complex to maintain and hard to grasp for new users.
Moreover, they are hardly testable.

**Feature**

I started the creation of a go tool to fully replace those scripts: https://github.com/FedeDP/dbg-go

Opening this  to track it.

It needs to replace:
- [x] utils/scrape_and_generate
- [x] utils/generate
- [x] utils/checkfiles
- [x] utils/cleanup_s3
- [x] utils/driverstats
- [x] utils/build

plus all the Makefile's logic.

Note: the actual repo will be donated to falcosecurity asap (i want to add some tests and release pipelines); then https://github.com/falcosecurity/test-infra/pull/1204 will be rebased to use the new repo published artifacts (versioned).

Moreover, the first and most important aim for the tool is to be used in the `update-dbg` job; that's why i implemented `generate,scrape_and_generate` first.
Once the tool gains support for all utils, we'll just drop all of them and the Makefile from the driverkit/ folder, update `build-drivers` image entrypoint to use the new tool, and rewrite the driverkit/ folder documentation (readme file).

**Comment by FedeDP** [comment]
Since the `dbg-go` tool implements everything needed, i am updating #1204 to the new tool.
Note: `dbg-go` tool still needs to be donated; i will open the issue in the next few days.

**Comment by LucaGuerra** [comment]
Just wanted to comment that you probably know how much I LOVE this <3 . Just reading the title makes me happy.

**Comment by FedeDP** [comment]
Also @LucaGuerra since you are interested, can you vote here? https://github.com/falcosecurity/evolution/issues/316 :) Thanks!
