### ISSUE TITLE
pre-built eBPF probe seems to be halfway missing for amazonlinux

### ISSUE THREAD

**Issue by timothy-spencer** [falcosecurity/test-infra#135]
**Describe the bug**

When I try to run falco on an EKS cluster, it tries to download `https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.o`, which does not exist.  However, `https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.ko` does, so maybe the build process needs to be fixed?

**How to reproduce it**

```
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
kubectl config set-context --current --namespace=kube-system
cat <<EOF > falco-values.yml
ebpf:
  enabled: true
  settings:
    mountEtcVolume: false
EOF
helm template --name-template=falco falcosecurity/falco -f falco-values.yml > falco.yml
kubectl apply -f falco.yml
kubectl logs daemonset.apps/falco -n kube-system
```

**Expected behaviour**

I expect the falco image to be able to successfully download the appropriate amazonlinux .o file so that it can load it and run.

**Screenshots**

```
laptop:~$ kubectl logs daemonset.apps/falco -n kube-system 
Found 4 pods, using pod/falco-8xb4p
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Found kernel config at /host/boot/config-4.14.177-139.254.amzn2.x86_64
* Trying to compile the eBPF probe (falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.o)
make[1]: *** /lib/modules/4.14.177-139.254.amzn2.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-96bd9bc560f67742738eb7255aeb4d03046b8045/bpf/probe.o': No such file or directory
* Trying to download a prebuilt eBPF probe from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.o
curl: (22) The requested URL returned error: 404 Not Found
Download failed
Wed Jun 10 20:34:47 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Jun 10 20:34:47 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Jun 10 20:34:48 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Jun 10 20:34:49 2020: Unable to load the driver. Exiting.
Wed Jun 10 20:34:49 2020: Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': Errno 2. Exiting.
laptop:~$ 
```

**Environment**

AWS EKS 1.16

- Falco version:  image: docker.io/falcosecurity/falco:0.23.0
- System info:
- Cloud provider or hardware configuration:
- OS:
- Kernel:  falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1
- Installation method:  Kubernetes, from rendered helm template (documented above)

**Additional context**

None that I can think of!  Thanks for your help!

**Comment by timothy-spencer** [comment]
Thanks for the information.  Turning off eBPF does indeed work.  I have a vague memory of turning this on because some documentation said I needed to, perhaps while I was trying to test it out in AWS Fargate.  

Anyways, it's working now.  Thanks again!

**Comment by fntlnz** [comment]
Amazonlinux support was just added in test-infra. See https://github.com/falcosecurity/test-infra/pull/139
