### ISSUE TITLE
Rename test-infra

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/test-infra#136]
**Motivation**

I believe the name `test-infra` is misleading. 

This repository seems to hold configuration for falco infrastructure. I don't even see anything related to testing in here.

Can we rename this to `infrastructure` or something a little more relevant? There are issues like https://github.com/falcosecurity/falco/issues/1262 that I believe could be mitigated if folks had a better understanding of this repository and what it's used for. 

**Feature**

**Alternatives**

**Additional context**

**Comment by nibalizer** [comment]
+1

**Comment by maxgio92** [comment]
Hi all,
is this still relevant in your opinion, also now that this repository holds (and step by step will hold more) the CI pipelines?
Thank you
