### ISSUE TITLE
Area userspace in Falco repo

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/test-infra#155]
**Motivation**

We have an area for every type of driver in the Falco repo:

- area/bpf-probe
- area/kernel-module

**Feature**

We need an area for userspace instrumentation too for when issues and PRs are opened on that:

- area/userspace

**Alternatives**

**Additional context**

This is needed for when userspace instrumentation is merged into Falco https://github.com/falcosecurity/falco/pull/1195

**Comment by leodido** [comment]
Label created: https://github.com/falcosecurity/falco/labels/area%2Fuserspace-instrumentation

**Comment by leodido** [comment]
Can we close this?
