### ISSUE TITLE
Move test-infra to AWS

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/test-infra#159]
**Motivation**

The Falcosecurity test infra is heavily based on [Prow](https://github.com/kubernetes/test-infra/).

Right now, we are able to use prow in our cluster on Packet, however:

- Maintaining and operating a kubernetes cluster on Packet is a task that needs care and maintenance (see https://github.com/falcosecurity/test-infra/issues/122)
- We are not able to have a stateful prow cluster on Packet without writing custom software for it or installing other components (that also need maintenance)

Said that, we had a discussion with @jonahjon from AWS and they are here to support us with credits for the project.

**Feature**

- Start an EKS cluster on AWS
- Install prow on it

**Alternatives**

**Additional context**

This was already decided as a yes in our community calls.
Notes [here](https://github.com/falcosecurity/community/blob/8f54955e06d4f9b083b559a29a44e7d0d5350c9f/meeting-notes/2020-07-01.md)

**Comment by fntlnz** [comment]
Here is an architecture diagram for what we need on AWS as asked by them while in the process of getting the credits approved.

![Kubernetes Falcosecurity](https://user-images.githubusercontent.com/3083633/89038368-81f66e00-d340-11ea-807d-c8e78a0219a2.png)

The worker nodes autoscaling group and the bastion host will be instance types `t2.medium`.

**Comment by fntlnz** [comment]
YAY! AWS just approved the budget for us!!!

**Comment by leodido** [comment]
A rough estimate of the cost is ~260$/mo.

More details [here](https://calculator.s3.amazonaws.com/index.html#r=MXP&key=files/calc-df37178d65d697429fa6aeb5da832e7a67e7e91e&v=ver20200916q9) (add ~80$/mo on top of that for EKS usage).

**Comment by leodido** [comment]
The migration is done! Thanks to @jonahjon and @maxgio92!  🥳 

/close
