### ISSUE TITLE
Falco Complication with EKS

### ISSUE THREAD

**Issue by tsmith60** [falcosecurity/test-infra#213]
Falco is having issues deploying to EKS using the helm chart and/or pod definition. It has an issue with pulling the eBPF probe when that method is enabled. The default method is not able to be pulled either.  I believe that the source of the issue is related to using EKS with managed node groups. Automatic node updates are killing the falco implementation everytime AWS gets a version ahead of the precompiled drivers.

<img width="1204" alt="Screen Shot 2020-11-17 at 11 17 41 AM" src="https://user-images.githubusercontent.com/25671827/99440396-85f4ce80-28e4-11eb-875e-a24b9fff1cac.png">
<img width="1212" alt="Screen Shot 2020-11-17 at 2 56 36 PM" src="https://user-images.githubusercontent.com/25671827/99440870-2945e380-28e5-11eb-85e7-dbdf6d09ae2f.png">
[falco_helm_values_v3.yaml.zip](https://github.com/falcosecurity/test-infra/files/5555906/falco_helm_values_v3.yaml.zip)

.

**Comment by nonamef** [comment]
Fixed by https://github.com/falcosecurity/test-infra/pull/219
