### ISSUE TITLE
Setup PR status page

### ISSUE THREAD

**Issue by leodido** [falcosecurity/test-infra#23]
<img width="1897" alt="image" src="https://user-images.githubusercontent.com/120051/59070110-c069d780-88b9-11e9-8096-1185ad7185c8.png">

**Comment by leodido** [comment]
/remove-lifecycle rotten

I believe the Falco Infra WG would like to work on this a bit.

**Comment by leodido** [comment]
/remove-lifecycle stale

@jonahjon wouldn't be rad to have this too? :)

**Comment by jonahjon** [comment]
Is there any info on how this is configured?

**Comment by jonahjon** [comment]
Looks we need to setup Oauth to make this work https://github.com/kubernetes/test-infra/blob/4bb9fe31555e88329da3772f812fb8e64f816125/prow/cmd/deck/main.go#L585

**Comment by maxgio92** [comment]
[Here](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/github_oauth_setup.md) we have the guide from Kubernetes' `test-infra`.

**Comment by maxgio92** [comment]
I'm working on this
