### ISSUE TITLE
Correctly configure $CLONEREFS_OPTIONS env variables

### ISSUE THREAD

**Issue by leodido** [falcosecurity/test-infra#265]
**Motivation**

By looking at [this](https://github.com/falcosecurity/test-infra/pull/264/commits) I noticed that the `autobump` component
does not commit with @poiana user (while the PR gets correctly opened by @poiana).

**Feature**

Clonerefs can be configured by either passing in flags or by specifying a full set of options as JSON in the $CLONEREFS_OPTIONS environment variable, which has the form:

```json
{
    "src_root": "...",
    "log": "...",
    "git_user_name": "THIS",
    "git_user_email": "AND@THIS",
    "refs": [
        {
            "org": "kubernetes",
            "repo": "test-infra",
            "base_ref": "master",
            "base_sha": "...",
            "pulls": [
                {
                    "number": 123,
                    "author": "...",
                    "she": "..."
                }
            ],
            "skip_submodules": true,
            "clone_depth": 0
        }
    ]
}
```

**Comment by maxgio92** [comment]
I think this has been solved, WDYT @leodido ? Thanks
