### ISSUE TITLE
Two ALB ingress controller versions deployed

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#293]
**Describe the bug**

Two versions of ALB ingress controller are currently running, onw 2.0.0 and 1.1.8.
The last one with one replicaset without currently pods running because of the missing service account.

**How to reproduce it**

```
kubectl get deploy -n kube-system
kubectl get rs -n kube-system
kubectl get events -n kube-system
```

**Solution**

Maybe we can remove the `alb-ingress-controller` ingress controller that runs the 1.1.8 version.
To investigate.

**Comment by jonahjon** [comment]
This was not tracked/deleted correctly when we upgraded from the `alb-ingress-controller` to the `aws-load-balancer-controller`. Since it was not tracked in the the prow yaml, just went and deleted it from the cluster. Closing the issue.
