### ISSUE TITLE
@poiana's commit signature doesn’t match the committer email

### ISSUE THREAD

**Issue by leogr** [falcosecurity/test-infra#354]
**Describe the bug**

@poiana's commits are not verified anymore, because the email in the commit signature doesn’t match the committer email.
The issue was introduced by #336

**How to reproduce it**

Just take a look to a PR opened by @poiana , for example: https://github.com/falcosecurity/evolution/pull/55

**Expected behaviour**

**Screenshots**

![Screenshot from 2021-03-31 09-22-55](https://user-images.githubusercontent.com/3390997/113106248-d705bf00-9202-11eb-8393-fd9d8a339d09.png)

**Comment by jonahjon** [comment]
Is this still occurring, I didn't see it on a recent PR

**Comment by leogr** [comment]
Yes, it's still occurring recently (here an example https://github.com/falcosecurity/evolution/pull/68/commits )
AFAIK it was tentatively fixed by https://github.com/falcosecurity/test-infra/pull/336 but likely there's something more to address.

**Comment by maxgio92** [comment]
The current key email matches the old email address, not the new one.
I generated a new keypair that matches, rotated in the cluster and authorized in Github.
I opened a PR to update the fingerprints [here](https://github.com/falcosecurity/test-infra/pull/559).
