### ISSUE TITLE
Upgrade EKS Cluster to current Version 1.19

### ISSUE THREAD

**Issue by jonahjon** [falcosecurity/test-infra#370]
**Motivation**

Need to upgrade 6 items in the EKS cluster on the quarterly basis going forward to maintain security. 
- EKS Control plane Version
- EKS Data plane version
- EKS optimized AMI ID
- VPC CNI image tag/version
- EKS Kubelet version
- CoreDNS tag/version

Will create one of these for each quarterly EKS version release going forward.

**Comment by maxgio92** [comment]
I think we can close this @jonahjon , what do you think?
We could also opening it recurrently mmm

**Comment by maxgio92** [comment]
Let's see with #437 :D
