### ISSUE TITLE
Validate Terraform plan before approving it

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#391]
**Describe the bug**

The workflow now is real continuous deployment of infrastructure, but I propose to introduce approval of Terraform plans before applying them, even if they are tested locally - as it might not be the case.

**How to reproduce it**

Edit code under `config/clusters`, open a PR, merge the PR.

**Expected behaviour**

The validation in the PR should also preview the Terraform plan so that we'll scan the code from a functional perspective, other than scanning it from a security perspective only.

**Examples**

[Build #877](https://app.circleci.com/pipelines/github/falcosecurity/test-infra/877/workflows/e67dc880-2a9b-4fb3-8f32-87098e4ceeb1/jobs/3563)

**Comment by leogr** [comment]
Has this been fixed? Or is it still an issue?

**Comment by maxgio92** [comment]
Still an issue. Maybe we can consider it an improvement on visibility.
WDYT?

**Comment by zuc** [comment]
Hey @maxgio92, are you maybe looking at something like https://www.runatlantis.io/?
I'll be happy to help here if you need it 🙂

**Comment by maxgio92** [comment]
hi @zuc ! Yeah that is the type of flow I'd like to follow. As a first step just a `terraform plan` running in a `presubmit` Prow job, could do quick & dirty work. 
Sure, I'll let you know, thank you!

**Comment by maxgio92** [comment]
I'm going to close this issue in favour of FR #396 (more appropriate type).
/cc @zuc @leogr
