### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by r8474** [falcosecurity/test-infra#395]
**Describe the bug**

`falco_amazonlinux2_4.14.231-173.361.amzn2.x86_64_1.ko` is not present in the [download repository](https://download.falco.org/5c0b863ddade7a45568c0ac97d037422c9efb750/falco_amazonlinux2_4.14.231-173.361.amzn2.x86_64_1.ko) despite existing in the [config folder](https://github.com/falcosecurity/test-infra/blob/master/driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.231-173.361.amzn2.x86_64_1.yaml). From looking at the logs of the Prow [build-drivers-amazonlinux-periodic](https://prow.falco.org/view/s3/falco-prow-logs/logs/build-drivers-amazonlinux-periodic/1394125573395058688) job it was never picked up.

**Expected behaviour**

All Kernel modules are built.

**Additional context**

We require this Falco module.

**Comment by bakalor** [comment]
Mentioned module should be built by [amazonlinux2 job](https://prow.falco.org/view/s3/falco-prow-logs/logs/build-drivers-amazonlinux2-periodic/1391951230095331328). But this job has even bigger problems.

**We also extremely need mentioned module.** 

By the way, to which repo mentioned CI push artifacts, to deprecated bintray or to new download.falco.org ?

Thanks.

**Comment by maxgio92** [comment]
Thanks @r8474 and @bakalor to notify the issue. We're investigating and remediating to publish drivers for AL2

**Comment by bakalor** [comment]
It works now, thank you very much!

**Comment by maxgio92** [comment]
Thank you @bakalor for the rapid feedback!
In example [this](https://download.falco.org/driver/2aa88dcf6243982697811df4c1b484bcbe9488a2/falco_amazonlinux2_4.14.231-173.361.amzn2.x86_64_1.ko) is the link to the driver for AL2. Is it ok also for you @r8474?
