### ISSUE TITLE
poiana comment has a broken link to contributing guide

### ISSUE THREAD

**Issue by Rajakavitha1** [falcosecurity/test-infra#430]
**What is wrong with the website or needs to be cleaned?**

The link now points to https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md and results in 404.

Update the link to https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md

<img width="749" alt="Screenshot 2020-11-22 at 3 30 18 PM" src="https://user-images.githubusercontent.com/37059749/99900781-bd45ef80-2cd7-11eb-91cf-1264570215e6.png">

**Comment by leogr** [comment]
Hey

it seems to me that #431 fixed another issue, since the "contributing guide" link is still pointing to a wrong URL. My test here:
https://github.com/falcosecurity/falco-website/pull/474#issuecomment-871200881

It was reported again in https://github.com/falcosecurity/falco-website/issues/473

/reopen

**Comment by leogr** [comment]
Additional context:
- the root issue seems to be in the way the dco plugin is formatting the URL :point_right: https://github.com/kubernetes/test-infra/blob/master/prow/plugins/dco/dco.go#L206

**Comment by atarax665** [comment]
> Additional context:
> 
> * the root issue seems to be in the way the dco plugin is formatting the URL 👉 https://github.com/kubernetes/test-infra/blob/master/prow/plugins/dco/dco.go#L206

Yeah, I too figured out the same. Only feasible way to resolve this issue from my perspective is,

 I assume that the organization has a common Contributing Guide for all the repositories, so we can change ```targetURL := fmt.Sprintf("https://github.com/%s/%s/blob/master/CONTRIBUTING.md", org, repo)``` to ```targetURL := fmt.Sprintf("https://github.com/%s/.github/blob/master/CONTRIBUTING.md", org)``` or maybe we should keep the targetURL static as ```targetURL = "https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md"```.

PS: Though [falcosidekick](https://github.com/falcosecurity/falcosidekick) has its own [CONTRIBUTING.md](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) somehow.
 
Another way out can be to add a CONTRIBUTING.md in each repository as that would generate a valid URL through existing DCO plugin (check [here](https://github.com/falcosecurity/falcosidekick/pull/220#issuecomment-820723328) but I guess that will defeat the whole purpose of having ```falcosecurity/.github``` repository.

@leogr Please do share your insights.

**Comment by leogr** [comment]
> I assume that the organization has a common Contributing Guide (in /.github) for all the repositories, so we can change `targetURL := fmt.Sprintf("https://github.com/%s/%s/blob/master/CONTRIBUTING.md", org, repo)` to `targetURL := fmt.Sprintf("https://github.com/%s/.github/blob/master/CONTRIBUTING.md", org)` or maybe we should keep the targetURL static as `targetURL = "https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md"` because `org` will be `falcosecurity` for all the repositories.

I believe the main issue here is that we have to host and maintain our own customized DCO plugin. Once we have that, we could use a static URL or make it configurable on a per-repo basis.

> PS: Though [falcosidekick](https://github.com/falcosecurity/falcosidekick) has its own [CONTRIBUTING.md](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) somehow.
> 
> Another way out can be to add a CONTRIBUTING.md in each repository as that would generate a valid URL through existing DCO plugin (check [here](https://github.com/falcosecurity/falcosidekick/pull/220#issuecomment-820723328) but I guess that will defeat the whole purpose of having `falcosecurity/.github` repository.

The original idea was to have just one centralized CONTRIBUTING.md. And btw I still like that idea since it requires less maintenance. :smile_cat: 
I guess that once we solve the DCO plugin issue, even `falcosidekick` could use the centralized CONTRIBUTING.md.
@falcosecurity/falcosidekick-maintainers wdyt?

**Comment by Issif** [comment]
> I guess that once we solve the DCO plugin issue, even `falcosidekick` could use the centralized CONTRIBUTING.md.
> @falcosecurity/falcosidekick-maintainers wdyt?

Ok for me

**Comment by zuc** [comment]
I just opened https://github.com/kubernetes/test-infra/pull/25495 to address this, let's see if it goes through 🙂

**Comment by zuc** [comment]
The upstream PR just got merged yesterday (https://github.com/kubernetes/test-infra/pull/25495) so we can finally go ahead and fix this.

/remove-lifecycle stale
