### ISSUE TITLE
New Falco CI Infrastructure

### ISSUE THREAD

**Issue by markyjackson-taulia** [falcosecurity/test-infra#48]
Track the work being done for Falco infrastructure.

**Comment by leodido** [comment]
@markyjackson-taulia can you please add a bit more detail? :)

**Comment by markyjackson-taulia** [comment]
Adding more details here from a high level architectural perspective (consider this the umbrella issue):
- [] Jenkins X to build the infrastructure within Sysdig AWS infrastructure
- [] Integrate with Prow
- [] Build out the CI using Jenkins X as well
- [] Document

**Comment by markyjackson-taulia** [comment]
There will be more detailed items to come from each of the above items and I will track those via issues

**Comment by markyjackson-taulia** [comment]
Infrastructure has been built out as checked off above. I will now work to integrate prow and Jenkins
cc: @leodido & @fntlnz

**Comment by markyjackson-taulia** [comment]
I am ready to do the prow work

**Comment by rajibmitra** [comment]
Let me know if anyone needs a hand on this issue. Thanks.

**Comment by markyjackson-taulia** [comment]
There is an issue with billing here. Previously, sysdig was paying for the infra and that charge recently was denied and the infra we built got slated for termination. 
We need to determine the following now.
1. How do we split the billing if we choose to continue using GCP?
2. We could use the CNCF funded infra (Azure)
    a. If we choose to do this I will need to involve Luc to get access and all the details there (I personally think this is the easier happy path

**Comment by leodido** [comment]
Feeling like we need you here @kris-nova :)

Side note to @markyjackson-taulia:
AFAI (last time I checked) Prow does not have complete support for Azure. Could we verify this please?

**Comment by leodido** [comment]
BTW, this sounds like a topic to discuss during next office hours!

**Comment by markyjackson-taulia** [comment]
Agreed, I added it as a topic to the agenda notes

**Comment by markyjackson-taulia** [comment]
Initiating conversation with the CNCF @lucperkins

**Comment by rajibmitra** [comment]
Any update on this @markyjackson-taulia  @lucperkins

**Comment by markyjackson-taulia** [comment]
> Any update on this @markyjackson-taulia @lucperkins

Unfortunately no. I need to turn this over to @kris-nova to handle

**Comment by fntlnz** [comment]
I think we can close this, Falco is now on Circle CI and poiana is migrated to a CNCF owned kubernetes cluster on packet.
