### ISSUE TITLE
Kernel module and eBPF probe test and build grid

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/test-infra#53]
I'm not sure if we had an issue already for this, I wasn't able to find one.

One of the most important components of Falco itself is the mechanism that collects syscalls from the kernel. Such mechanism is based on a Kernel module or on an eBPF probe.

In both cases, the artifact needs to be built specifically for the kernel in use (sources and config flags).

What we want to do is to have a CI mechanism that can run a grid of jobs to build all those different combinations and push the final result to s3 or docker hub.

I'm saying s3 because that's the way we've been distributing those right now, we have a similar thing that it's hosted by Sysdig and we want to replace that with a community owned one.

I'm saying docker hub because the docker registry is a very good way to distribute artifacts and I know that @mfdii was doing some work on this in his PR about slim images https://github.com/falcosecurity/falco/pull/776

@markyjackson-taulia is working on a new CI mechanism for Falco based on JenkinsX #48 - we might want to integrate this there.

If integrating this in JenkinsX is not an option (we might not have enough fire power to do it or it's difficult to do a grid) another option since this week is to just continue using travis for this part.

@AkihiroSuda on the rootless containers project, recently discovered that full VMs can be run on Travis, we could do a kernel vmlinuz for each config and kernel version + a rootfs and build the probes on each one of them, then just run it on KVM on travis.

(opening this w/ @leodido)

**Comment by fntlnz** [comment]
Blocked by #48

**Comment by fntlnz** [comment]
This is moving forward, we've got access to the CNCF cluster to set this up there.

https://github.com/cncf/cluster/

**Comment by leodido** [comment]
This was done by @fntlnz and I long ago.

/close
