### ISSUE TITLE
Missing falco_ubuntu-aws_5.4.0-1059-aws_62.ko

### ISSUE THREAD

**Issue by wahern-splunk** [falcosecurity/test-infra#560]
The most recent Ubuntu AWS driver build pipeline ran on November 18th/19th (see https://prow.falco.org/view/s3/falco-prow-logs/logs/rebuild-all-drivers-ubuntu-aws-5-periodic/1461529845765771264), seemingly just before publication of the most recent Ubuntu 18.04 kernel, 5.4.0-1059-aws #62~18.04.1-Ubuntu.

How often is the driver build pipeline run? Weekly?

**Comment by evanmcclure** [comment]
This appears to work. Go ahead and close this, please.
