### ISSUE TITLE
Missing amazonlinux2_5.4.156-83.273 pre-built modules

### ISSUE THREAD

**Issue by frankgu968** [falcosecurity/test-infra#571]
**Describe the bug**
EKS Amazon Linux 2 node AMIs have been updated recently (Nov 17, 2021) to kernel version 5.4.156-83.273. However, currently, the highest kernel version being built by the build grid is only up to 5.4.149 causing many installations to be broken. This version should be added to the build grip. 

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by xavidop** [comment]
+1

**Comment by zuc** [comment]
Solved by #572.

/close
