### ISSUE TITLE
Prow fails to upload some probes

### ISSUE THREAD

**Issue by Issif** [falcosecurity/test-infra#585]
By running my script for testing if drivers are available before trying to install Falco ([see here](https://github.com/Issif/falco-driver-check)) I noticed that for some kernel versions, the module is available but not the probe, even if the driverkit config is correct.

For example, we have `falco_debian_5.10.0-9-amd64_1.ko` but not `falco_debian_5.10.0-10-amd64_1.o`.

I checked Prow logs and saw this behavior are full of this kind of error:
```
 INFO using config file                             file=config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/debian_5.10.0-9-amd64_1.yaml
INFO driver building, it will take a few seconds   processor=docker
INFO kernel module available                       path=output/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_debian_5.10.0-9-amd64_1.ko
FATA exiting                                       error="Error: No such container:path: d4d6e3669a68547893466dea135fff3dfef2071611f84c1c94437c7a1bacc38e:/tmp/driver/bpf/probe.o" 
```
Source: https://prow.falco.org/view/s3/falco-prow-logs/logs/rebuild-all-drivers-debian-periodic/1478924491085058048

cc @zuc @leogr

**Comment by leogr** [comment]
Have you tried to build them using a local installation of driverkit?

Note, there's no 100% guarantee that all probes can be built by driverkit (headers might be missing, wrong compiler version, etc..).

**Comment by Issif** [comment]
I tried myself and faced the same issue. I'm not the only one, here a PR from @LucaGuerra for fixing the issue.

**Comment by leogr** [comment]
cc @maxgio92 @zuc 

I believe this has not been fixed yet?

**Comment by maxgio92** [comment]
Exactly. The issue I think needs to be replicated and debugged. @LucaGuerra do you have more info on this?

To be noted that in the meantime Driverkit evolved and different issues have been solved.
