### ISSUE TITLE
Missing falco module for falco_ubuntu-generic_5.4.0-96-generic_109.ko

### ISSUE THREAD

**Issue by fredleger** [falcosecurity/test-infra#622]
**Motivation**

When launching Flaco pods on scaleway fresh cluster got the following:

```
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.30.0, driver version=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to load a system falco module, if present
* Looking for a falco module locally (kernel 5.4.0-96-generic)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_ubuntu-generic_5.4.0-96-generic_109.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
```

**Feature**

Would like to see this module built

**Alternatives**

**Additional context**

**Comment by fredleger** [comment]
would be pleased to contribute to it if there is a documented way of building it. Also can the urls be overrided in order to test it ?

**Comment by zuc** [comment]
Hi @fredleger - here's quick guide on how to add a missing configuration for a kernel module and/or ebpf probe: https://github.com/falcosecurity/test-infra/tree/master/driverkit#faq
