### ISSUE TITLE
Switch to kubernetes image-bumper instead of our autobumper script

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/test-infra#627]
**Motivation**

Our autobumper script is written in bash.

**Feature**

 https://github.com/kubernetes/test-infra/tree/master/prow/cmd/generic-autobumper is written in go and it is surely more maintenable.

**Alternatives**

**Additional context**

**Comment by maxgio92** [comment]
Thanks @FedeDP, sorry for the late response.
I honestly like the idea! I'll take a look at it.
