### ISSUE TITLE
Missing amazonlinux2_5.4.181-99.354 pre-built modules

### ISSUE THREAD

**Issue by xavidop** [falcosecurity/test-infra#662]
**Describe the bug**

EKS Amazon Linux 2 node AMIs have been updated recently, to kernel version 5.4.181-99.354. However, currently, the highest kernel version being built by the build grid is only up to5.4.156-83.273 causing many installations to be broken. This version should be added to the build grip.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by zuc** [comment]
Hi @xavidop - that kernel version has been added some hours ago by #657.
It seems to me that the kernel module has been correctly built by our build grid and publicly available here:

```
$ curl -I https://download.falco.org/driver/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_amazonlinux2_5.4.181-99.354.amzn2.x86_64_1.ko
HTTP/2 200
content-type: binary/octet-stream
content-length: 3846520
date: Fri, 18 Mar 2022 22:28:41 GMT
last-modified: Fri, 18 Mar 2022 11:32:40 GMT
etag: "fec0d670657f3d7612bbb96b2fd6b2d4"
accept-ranges: bytes
server: AmazonS3
x-cache: Hit from cloudfront
via: 1.1 d2845a19ef21fd46f750fc75a076b272.cloudfront.net (CloudFront)
x-amz-cf-pop: FCO50-P2
x-amz-cf-id: PHrLYeO7--6_jE9crI8B3plJ1PF--QhQW94t8XnZXZfYS3kKBBUDKw==
age: 2410
```

I'm gonna close this as it seems a non-issue, but feel free to reopen should you think my understanding is somehow incorrect.

/close

**Comment by xavidop** [comment]
hi @poiana Im sorry but while installing falco on our k8s cluster with that ami, it is still not finding that falco kernel:
 * Setting up /usr/src links from host                                                                                                                                                                                                                      │
│ * Running falco-driver-loader for: falco version=0.31.0, driver version=319368f1ad778691164d33d59945e00c5752cd27                                                                                                                                           │
│ * Running falco-driver-loader with: driver=module, compile=yes, download=yes                                                                                                                                                                               │
│ * Unloading falco module, if present                                                                                                                                                                                                                       │
│ * Looking for a falco module locally (kernel 5.4.181-99.354.amzn2.x86_64)                                                                                                                                                                                  │
│ * Trying to download a prebuilt falco module from https://download.falco.org/driver/319368f1ad778691164d33d59945e00c5752cd27/falco_amazonlinux2_5.4.181-99.354.amzn2.x86_64_1.ko                                                                           │
│ curl: (22) The requested URL returned error: 404

**Comment by xavidop** [comment]
nevermind, I just had to upgrade falco to the last version. thanks for the support! you rock!
