### ISSUE TITLE
Missing Driver falco_amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.ko

### ISSUE THREAD

**Issue by oc-christopher-billett** [falcosecurity/test-infra#680]
Motivation

When running Flaco pods on an EKS cluster I receive the following:

* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.31.1-136+120027d, driver version=b19f87e8aee663e4987a3db54570725e071ed105
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Looking for a falco module locally (kernel 5.4.188-104.359.amzn2.x86_64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/b19f87e8aee663e4987a3db54570725e071ed105/falco_amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco module

Feature

Would like to see this module built

Alternatives

Additional context

**Comment by maxgio92** [comment]
Thanks @oc-christopher-billett for this. Does the build of the driver fail after looking for a prebuilt one?
In the meantime @ianmuscat opened a PR (#681) to include also this kernel release to release a prebuilt driver for.

**Comment by ianmuscat** [comment]
@oc-christopher-billett can you give this another shot now that #681 is merged (worked for me)?

**Comment by oc-christopher-billett** [comment]
@ianmuscat working for me. Thank you
