### ISSUE TITLE
[Missing Driver]: falco_amazonlinux2_5.4.181-99.354.amzn2.x86_64_1.ko

### ISSUE THREAD

**Issue by iAnomaly** [falcosecurity/test-infra#706]
**Describe the bug**

Failing to start on Amazon Linux2 5.4.181-99.354:
```
* Looking for a falco module locally (kernel 5.4.181-99.354.amzn2.x86_64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_5.4.181-99.354.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404
```

**How to reproduce it**

Start Falco on Amazon Linux2 5.4.181-99.354. Startup fails because this driver is missing:
https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_5.4.181-99.354.amzn2.x86_64_1.ko

**Expected behaviour**

Startup succeeds because driver exists.

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method: AWS EKS Kubernetes 1.22 (Helm chart 1.16.2)

**Additional context**

**Comment by FedeDP** [comment]
@youngjeong46 in your case, it is a missing driver! Can you open a PR on test-infra to add it?

**Comment by maxgio92** [comment]
As of now, the module is published https://download.falco.org/driver/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.ko

**Comment by FedeDP** [comment]
So, i think this can be considered closed now :)

**Comment by maxgio92** [comment]
Thanks all. Anyway, do not hesitate to re-open this, if needed.
