### ISSUE TITLE
Introduce signature of OCI artifacts

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#722]
## Motivation

To improve the security of the supply chain, we'd like to provide signed container images, both are used internally in the open infrastructure (**step 1**) and ones are distributed (**step 2**), as they're public.
Also it could help to build verified SBOM.

This issue tracks the coverage of artifacts of the **Open Infra**.

## Feature

Introduce OCI artifacts signing with [cosign](https://github.com/sigstore/cosign), in CI pipelines.
The detail of where signin keypairs should be conserved is briefely explained below.

### Keypair bootstrap

| In-cluster | External | Hybrid |
| --- | --- | --- |
| `generate-key-pair` > K8s | `generate-key-pair` > vault | `generate-key-pair` > vault > K8s |

### Signing pipeline

| In-cluster | External | Hybrid |
| --- | --- | --- |
| K8s > `sign` > OCI | vault > `sign` > OCI | K8s > `sign` > OCI |

#### Keypair source of truth

| In-cluster | External | Hybrid |
| --- | --- | --- |
| K8s | vault | vault |

### Verification

| In-cluster | External | Hybrid |
| --- | --- | --- |
| K8s > `verify` < OCI | vault > `verify` < OCI | K8s > `verify` < OCI |

> Note: _vault_ is supposed to be an external (un)managed vault or specifically KMS managed services.

## Alternatives

When images are stored in AWS Elastic Container Registry, wait/contribute to ECR signing (issue [#43](https://github.com/aws/containers-roadmap/issues/43)).

## Status
- [ ] Signing (#835)
- [ ] Verification (#836)

**Comment by dlorenc** [comment]
Hey! I just saw this, feel free to reach out if you need any help!

**Comment by maxgio92** [comment]
Thank you @dlorenc!! I'll be in touch :-)

**Comment by maxgio92** [comment]
Hi @dlorenc @developer-guy in #752 an initial work with the keypair placed in the open infra Kubernetes cluster.

Key points:

- the main [sign](https://github.com/falcosecurity/test-infra/pull/752/files#diff-3eb94d8f3e814963f24f0cf9cda6ba32124697646e4b9f0ef04676fc810be6f0R27) command wrapped in the artifacts publish stage (called [here](https://github.com/falcosecurity/test-infra/pull/752/files#diff-77b75cae41d6171c9da7c38f170c3cdc3704632d4641b5dc761164751ccd8188R19))
- the [jobs](https://github.com/falcosecurity/test-infra/pull/752/files#diff-abaeae1d37cc452a4273ec72a7c0766791bd80ee8ab780391fb0f4f9fce3f582) with needed tailored [RBAC](https://github.com/falcosecurity/test-infra/pull/752/files#diff-24619b9fbcb1f4434d74ecf66b2ac90c85994077d034ffe24610a9b59d49d35f)

> Side note, the Kubernetes `Secret` is not actually the source of truth and the vault is instead external.
Anyway, I see this as a starting point.

Lastly, unfortunately this is not to easy to follow. Still, that PR is also going to simplify the whole path :-)

WDYT?

**Comment by maxgio92** [comment]
I limited the scope of this issue to the Open Infra's artifacts.

I propose to start in a pragmatic way, with an *in-cluster* **bootstrap** and **signing** (#752). Then implement **verification** of artifacts.

To be discussed as next step instead moving to externally managed vault (this could be leveraged to start migrating secrets from OP).

**Comment by dlorenc** [comment]
cc @cpanato and @puerco!

**Comment by cpanato** [comment]
roger! i can help on this :)
