### ISSUE TITLE
Failing build-new-drivers-amazonlinux2-presubmit

### ISSUE THREAD

**Issue by mcbarzi** [falcosecurity/test-infra#747]
**Which jobs are failing**:
seeing this error in the job https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/742/build-new-drivers-amazonlinux2-presubmit/1541688127691689984

**Which test(s) are failing**:
```
359.amzn2.x86_64_1.o)
utils/checkfiles config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
DRIVERKIT=/bin/driverkit S3_DRIVERS_BUCKET="falco-distribution" S3_DRIVERS_KEY_PREFIX="driver" SKIP_EXISTING=true utils/build config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
INFO using config file                             file=config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
INFO driver building, it will take a few seconds   processor=docker
FATA exiting                                       error="\"specify container image platform\" requires API version 1.41, but the Docker daemon API version is 1.38"
utils/checkfiles config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.243-185.433.amzn2.x86_64_1.yaml
```
**Since when has it been failing**:

**Test link**:
https://github.com/falcosecurity/test-infra/pull/742
**Reason for failure**:

**Anything else we need to know**:

**Comment by maxgio92** [comment]
Hey @mcbarzi thanks for pointing that out. #743 already fixed this issue. BTW in the meantime we can retry the job.

**Comment by FedeDP** [comment]
It is now up on download.falco.org!
Sorry for the inconvenience :) There has been quite a bit of work on driverkit and test-infra to support multi architectures (arm64) drivers builds, and a bug slipped in!

**Comment by maxgio92** [comment]
I think this can be closed now @mcbarzi
