### ISSUE TITLE
Automatically sync `config/org.yaml` when an `OWNERS` file gets updated

### ISSUE THREAD

**Issue by leogr** [falcosecurity/test-infra#777]
**Motivation**

We need to automate the way we manage repository permissions.

On the one hand, `OWNERS` files are honored by Prow. On the other hand, GitHub uses its settings which are enforced by Peribolos that applies settings we commit to [config/org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml).

Unfortunately, there's no automatic mechanism to sync the two. And manually synching them can't scale (see https://github.com/falcosecurity/test-infra/pull/776).

**Feature**

Introduce a mechanism to automatically update [config/org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml) when an `OWNERS` file gets updated.

**Alternatives**

Manual synch. Honestly, it's a pain.

**Additional context**

**Comment by leogr** [comment]
cc @jasondellaluce @maxgio92 @FedeDP

**Comment by maxgio92** [comment]
In the meantime, I got a cross check that this isn't supported by Peribolos https://github.com/kubernetes/test-infra/issues/28977

**Comment by maxgio92** [comment]
Update: a first v0.1.0 MVP version of the tool that would sync OWNERS' leaf approvers with a specific GitHub team in a Github organizations Peribolos configuration, is here: https://github.com/maxgio92/peribolos-owners-syncer.

**Comment by maxgio92** [comment]
@jasondellaluce suggested to create a Prow plugin in order to provide a webhook, instead of using jobs. I think it's viable leveraging the same logics of a command line tool such that.

At the same time, I have concerns about:
- efficiency: running a webhook listening for rare events such that changes on OWNERS files across the organization. Not a big deal anyway IMHO.
- lock-in: that would stick us on Prow architecture. 

What about centralizing the automation first, by using pre-submit `ProwJobs`  that would trigger only on `.*OWNERS` file change, for each repository?

I'm thinking about Prow Jobs as I don't think this kind of automation is related to the repositories CI, for which we're choosing to leverage Github Actions, configured distributed on each the repository.

WDYT @falcosecurity/test-infra-maintainers?

**Comment by FedeDP** [comment]
> What about centralizing the automation first, by using pre-submit ProwJobs that would trigger only on .*OWNERS file change, for each repository?

That would be great; basically we will have a single yaml `owners_watcher.yaml` with all the `post-submit` jobs for each monitored repo, right? I don't love the fact that we need to manually add any new repo to this "watched list"; at the same time, this is the prow way of doing things.
And yes, i fully agree that this is an organization management job, and thus should be kept on prow.

Basically, it would become part of adding a new repo on test-infra, adding it to the `owners_watcher.yaml`.

**Comment by maxgio92** [comment]
This is a sample PR: https://github.com/falcosecurity/test-infra/pull/1049 with an update to `evolution-maintainers` (no effect, besides alphabetical re-order and add of all the leaf approvers to the related maintainers GitHub Team's members).

**Comment by leogr** [comment]
hey @maxgio92 @FedeDP 
I'm slightly off-topic, but I wanted to highlight one possible implementation issue.

Although it is usually possible to update `config/org.yaml` by fetching data from `OWNERS` files, there's a case when this can't be done.

When an open PR tries to modify an `OWNERS` file by introducing a new user (that's not already part of the organization), we have to update the [members](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml#L21) field of `config/org.yaml` (to send the invite to the new member to join the org) **before** merging the PR (thus before the `OWNERS` file gets updated). Otherwise, it would be possible to merge the PR if the new user still needs to join the org.

Please take this into account.

**Comment by maxgio92** [comment]
You're right @leogr, we missed this bit. So, when a proposal of a new reiviewer/approver on OWNERS is submitted via PR.

A possible flow, in case a new approver who will be a new Github organization's member is being added:

- a PR with update of the root OWNERS file is opened on the interested repository
- the verify-owners Prow plugin holds the PR as the user is not part of the Github organization
- votation happens
- if the quorum is reached, the user needs to be added as member of the org, so a first PR to the org.yaml repository - now test-infra - is opened
- the first PR on the org.yaml is merged
- the verify-owners Prow plugin unholds the PR
- the PR is merged
- the PR merge triggers the post-submit Prow Job with the tool to update the related maintainers GitHub Team
- the tool opens a second PR to the org.yaml updating the related Github Team
- the second PR is merged
- the user is member of the Github organization, Github maintainers team and is an approver for the interested repository.

Reference: https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS_GUIDELINES.md#onboarding-a-maintainer

**Comment by maxgio92** [comment]
As a side note, maybe a next feature, is to update the [Core Maintainers](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#core-maintainers)' Github Team too, when the project is a [Core Repository](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#core-repositories).
