### ISSUE TITLE
Upgrade Prow autobumper

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#856]
**Motivation**

Open Infra is using the previous version of the Kubernetes Prow autobumper, which is suboptimal based on functionalities and the fact that is not actively maintained.

**Feature**

We can reference the new Prow [Autobumper](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/generic-autobumper#autobumper) and using it as artifact - as done [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L592).

**Improvement**

This way requires in any case to statically declare the periodic Jobs for each repository that contains Prow component configuration (e.g. Peribolos) explicitely, and it's error prone.

It would be good to find a way to autobump Prow components dynamically discovering all the repositories that use them (i.e. now, test-infra and evolution).

**Related**

See #840

**Comment by maxgio92** [comment]
cc @zuc

**Comment by maxgio92** [comment]
I think this has been completed, isn't it @cappellinsamuele?

**Comment by cappellinsamuele** [comment]
Yep, almost completed! I'd wait for #1132 and #1133 to be merged before closing this issue, WDYT?

**Comment by maxgio92** [comment]
Yep, I agree!
