### ISSUE TITLE
Missing module for 3.10.0-1160.81.1.el7.x86_64 kernel version

### ISSUE THREAD

**Issue by ttryf** [falcosecurity/test-infra#953]
**Describe the bug**

`falco_centos_3.10.0-1160.81.1.el7.x86_64_1.ko` module isn't present on the download repository.
 
As per https://github.com/falcosecurity/test-infra/commit/020328419cc4778358482676db36188d1fc48437#diff-bf99cd9d9102e23ce7f0366638613ab29453ac2b0c656ed5dd06994b568a4922 commit, support for `3.10.0-1160.81.1` kernel version was introduced for version `2.0.0` of the driver.

YAML validation is successful based on [validate-new-drivers-centos-3-presubmit](https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/949/validate-new-drivers-centos-3-presubmit/1615008498192486400) job. According to the build log, it applies to the following driver versions:

```
2.0.0
3.0.1
4.0.0
```

**Expected behaviour**

Module is available on the download section, for the driver versions that is supposed to be shipped.

**Comment by FedeDP** [comment]
Hi! Possibly driverkit is not able to build it?

**Comment by FedeDP** [comment]
Exactly:
```
DEBU   LD [M]  /tmp/driver/falco.o
DEBU �ld: /tmp/driver/tp_table.o: invalid string offset 1819042147 >= 21 for section `mtab'
DEBU /tmp/driver/tp_table.o: error adding symbols: File format not recognized
DEBU Gmake[2]: *** [scripts/Makefile.build:470: /tmp/driver/falco.o] Error 1
DEBU :make[1]: *** [Makefile:1316: _module_/tmp/driver] Error 2
DEBU )make[1]: Leaving directory '/tmp/kernel'
```

Most of the times, errors like this are caused by a gcc version mismatch (perhaps the gcc that built this kernel had some minor patch applied).
It seems we would need a centos driverkit builder image to be able to build this one :/

**Comment by FedeDP** [comment]
A new driverkit version was released and updated on test-infra repo. Next Monday all the 3.10.0 CentOS driver should be built fine.

**Comment by FedeDP** [comment]
Hi! Is this issue still alive?
